apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initial-config
  labels:
    {{- include "acestream-scraper.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "urls": [],
      "base_url": "https://scraper.tonioriol.com/ace/getstream?id=",
      "ace_engine_url": "http://{{ .Values.env.ACESTREAM_HTTP_HOST }}:{{ .Values.env.ACEXY_PORT | default "8080" }}",
      "rescrape_interval": 30
    }
