{{- if .Values.auth.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "acestream-scraper.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-auth
    creationPolicy: Owner
  data:
    - secretKey: AUTH_USERNAME
      remoteRef:
        key: acestream-scraper
        property: username
    - secretKey: AUTH_PASSWORD
      remoteRef:
        key: acestream-scraper
        property: password
{{- end }}
