{{- if or .Values.auth.enabled .Values.acexyToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "acestream-scraper.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.enabled }}
  AUTH_USERNAME: {{ .Values.auth.username | quote }}
  AUTH_PASSWORD: {{ .Values.auth.password | quote }}
  {{- end }}
  {{- if .Values.acexyToken }}
  ACEXY_TOKEN: {{ .Values.acexyToken | quote }}
  {{- end }}
{{- end }}
