{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "acestream-scraper.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_USERNAME: {{ .Values.auth.username | quote }}
  AUTH_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
