apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "acestreamio.labels" . | nindent 4 }}
  {{- if .Values.externalDns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDns.hostname | quote }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.externalDns.target | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "acestreamio.labels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http

