{{- if .Values.auth.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACEXY_TOKEN
      remoteRef:
        key: acestream-scraper
        property: password
{{- end }}
