{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.issuer }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: {{ .Values.letsencrypt.server }}
    privateKeySecretRef:
      name: {{ .Values.tls.issuer }}-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
{{- end }}
