apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tonioriol/ritchie
    targetRevision: main
    path: charts/argocd-ingress
    helm:
      values: |
        # Override these values with your actual domain and email
        host: argocd.example.com
        letsencrypt:
          email: admin@example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
