apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "code.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: code.tonioriol.com
    external-dns.alpha.kubernetes.io/target: 85e6bc75-0025-4fc3-9341-d4e517fea614.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ClusterIP
  ports:
    - port: 14500
      targetPort: xpra
      protocol: TCP
      name: xpra
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "code.labels" . | nindent 4 }}
