apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: {{ .Values.tunnelId }}
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
{{- range .Values.hosts }}
      - hostname: {{ .hostname | quote }}
        service: {{ .service | quote }}
{{- end }}
      - service: http_status:404
